language: scala

scala:
  - 2.11.11
  - 2.12.3

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)